#!/usr/bin/env bash

#Destroying wild test containers
echo "Destroying stray test containers"
docker-compose stop test_web test_db test_redis
docker-compose rm -f test_web test_db test_redis

echo "Running tests"
docker-compose run test_web

#Destroying test containers normally
echo "Destroying test containers"
docker-compose stop test_web test_db test_redis
docker-compose rm -f test_web test_db test_redis